name: 'Changed File Filter'
description: 'A customisable filter that uses git to get changed files based on rules and sets them to outputs'
author: 'Jethro Muller'
inputs:
  change-map:
    required: true
    description: 'A map of changes to find. eg. {"python_files": "*.py", "requirements": "requirements/*.txt"}'
runs:
  using: 'node12'
  main: 'dist/index.js'
