name: 'Changed File Filter'
description: 'A customisable filter that uses git to get changed files based on rules and sets them to outputs'
author: 'Jethro Muller'
inputs:
  base-branch:
    required: false
    description: 'The name of the branch being compared to. Uses $GITHUB_BASE_REF if not set'
    default: $GITHUB_BASE_REF
  command:
    required: false
    description: 'The command to run to get the file changes can contain {glob} and {branchName} to specify replacements'
    default: 'git diff --name-status --no-renames {branchName} {glob}'
  change-filters:
    required: false
    description: >-
      A comma separated list of key value pairs (colon separated).
      Any defined keys will be kept, others discarded.
      Spaces around commas will not be trimmed to preserve all whitespace.
    default: 'ADDED:A\t,CHANGED:M\t,DELETED:D\t'
  change-map:
    required: true
    description: >-
      A multi-line map of changes to find.
      eg. python_files: ["*.py", false]
      requirements: ["requirements/*.txt"]
      The final boolean determines if we separate out floats
outputs:
  any-matches:
    description: 'Any glob matches found'
runs:
  using: 'node12'
  main: 'dist/index.js'
