name: 'Changed File Filter'
description: 'A customisable filter that uses git to get changed files based on rules and sets them to outputs'
author: 'Jethro Muller'
inputs:
  base-branch:
    required: false
    description: 'The name of the branch being compared to. Uses $GITHUB_BASE_REF if not set'
    default: $GITHUB_BASE_REF
  command:
    required: false
    description: 'The command to run to get the file changes can contain {glob} and {branchName} to specify replacements'
    default: 'git diff --name-status --no-renames {branchName} {glob}'
  filter-patterns:
    required: false
    description: >-
      A map with keys ADDED, CHANGED, and DELETED as keys and a pattern object ({"pattern": "<pattern>"}) as a value.
      Any defined keys will be kept, others discarded. Special characters should be escaped.
      The matching is done by checking if the file change starts with the pattern.
    default: |
      ADDED: {"pattern": "A\t"}
      CHANGED: {"pattern": "M\t"}
      DELETED: {"pattern": "D\t"}
  change-map:
    required: true
    description: >-
      A multi-line map of changes to find.
      eg. python_files: {"glob": "*.py", "separateDeleted": false}
      requirements: {"glob": "requirements/*.txt"}
      The final boolean determines if we separate out floats
outputs:
  any-matches:
    description: 'Any glob matches found'
runs:
  using: 'node12'
  main: 'dist/index.js'
