name: 'Changed File Filter'
description: 'A customisable filter that uses git to get changed files based on rules and sets them to outputs'
author: 'Jethro Muller'
inputs:
  base-branch:
    required: true
    description: 'The name of the branch being compared to. ${{ github.base_ref }} should work'
  change-map:
    required: true
    description: >-
      A multi-line map of changes to find.
      eg. python_files: "*.py", false.
      The final boolean determines if we separate out floats
outputs:
  any-matches:
    description: 'Any glob matches found'
runs:
  using: 'node12'
  main: 'dist/index.js'
