name: 'build-test'
on: [pull_request]

jobs:
  build-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all

  test-action: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          base-branch: "test_changes"
          command: "cat ./__tests__/{branchName}.txt"
          change-map: >-
            test: {"glob": "*.txt"}
            test-separate: {"glob": "*.txt", separateDeleted: true}
